import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from 'crypto'
export type OAuthCiphertext = { ciphertext: string; iv: string; tag: string }
type Runtime = Record<string, string | undefined>
export function getGoogleOAuthSetupError(env: Runtime = process.env): string | null { if (!env.GOOGLE_OAUTH_CLIENT_ID || !env.GOOGLE_OAUTH_CLIENT_SECRET) return 'GOOGLE_OAUTH_NOT_CONFIGURED'; if (!env.GOOGLE_TOKEN_ENCRYPTION_KEY || !/^[0-9a-f]{64}$/i.test(env.GOOGLE_TOKEN_ENCRYPTION_KEY)) return 'GOOGLE_TOKEN_ENCRYPTION_KEY_MISSING'; return null }
function key(value: string) { return Buffer.from(value, 'hex') }
export function encryptOAuthToken(value: string, encryptionKey: string): OAuthCiphertext { const iv=randomBytes(12); const cipher=createCipheriv('aes-256-gcm',key(encryptionKey),iv); const ciphertext=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]); return {ciphertext:ciphertext.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64')} }
export function decryptOAuthToken(value: OAuthCiphertext, encryptionKey: string): string { const decipher=createDecipheriv('aes-256-gcm',key(encryptionKey),Buffer.from(value.iv,'base64')); decipher.setAuthTag(Buffer.from(value.tag,'base64')); return Buffer.concat([decipher.update(Buffer.from(value.ciphertext,'base64')),decipher.final()]).toString('utf8') }
export function createOAuthState(userId:string, nonce:string, encryptionKey:string) { const payload=Buffer.from(JSON.stringify({userId,nonce,expiresAt:Date.now()+600000})).toString('base64url'); const signature=createHmac('sha256',encryptionKey).update(payload).digest('base64url'); return payload+'.'+signature }
export function verifyOAuthState(state:string, encryptionKey:string): {userId:string;nonce:string}|null { const [payload,signature]=state.split('.'); if(!payload||!signature)return null; const expected=createHmac('sha256',encryptionKey).update(payload).digest('base64url'); if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null; try { const parsed=JSON.parse(Buffer.from(payload,'base64url').toString('utf8')); return typeof parsed.userId==='string'&&typeof parsed.nonce==='string'&&Number.isFinite(parsed.expiresAt)&&parsed.expiresAt>Date.now()?{userId:parsed.userId,nonce:parsed.nonce}:null } catch { return null } }
