'use client'
import { useMemo, useState } from 'react'
import { Building2, Mail, Phone, Plus, Search, UserRound, Users } from 'lucide-react'

type Contact={id:string,name:string,phone:string|null,email:string|null,title:string|null,photoUrl:string|null,linkedinUrl:string|null,instagramUrl:string|null,websiteUrl:string|null,clientId:string|null}
type Company={id:string,name:string}

export default function ContactsClient({initial,companies}:{initial:Contact[],companies:Company[]}){
  const [items,setItems]=useState(initial),[query,setQuery]=useState(''),[filter,setFilter]=useState('TODOS'),[open,setOpen]=useState(false),[message,setMessage]=useState('')
  const [form,setForm]=useState({name:'',phone:'',email:'',title:'',photoUrl:'',linkedinUrl:'',instagramUrl:'',websiteUrl:'',clientId:''})
  const filtered=useMemo(()=>items.filter(item=>{const q=query.toLowerCase();const matches=!q||[item.name,item.email,item.phone,item.title].some(v=>String(v||'').toLowerCase().includes(q));const kind=filter==='VINCULADOS'?Boolean(item.clientId):filter==='SEM_VINCULO'?!item.clientId:true;return matches&&kind}),[items,query,filter])
  const linked=items.filter(x=>x.clientId).length
  const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value}))
  async function add(e:React.FormEvent){e.preventDefault();const payload=Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v||null]));const res=await fetch('/api/contatos',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!res.ok){setMessage('Não foi possível salvar o contato.');return}const data=await res.json();setItems(x=>[...x,data.contact]);setForm({name:'',phone:'',email:'',title:'',photoUrl:'',linkedinUrl:'',instagramUrl:'',websiteUrl:'',clientId:''});setMessage('Contato salvo com sucesso.');setOpen(false)}
  return <div className="space-y-5">
    <div className="grid gap-3 grid-cols-2 lg:grid-cols-4"><Metric label="Contatos" value={items.length} icon={<Users/>} tone="cyan"/><Metric label="Vinculados a clientes" value={linked} icon={<Building2/>} tone="emerald"/><Metric label="Sem vínculo" value={items.length-linked} icon={<UserRound/>} tone="amber"/><Metric label="Com telefone" value={items.filter(x=>x.phone).length} icon={<Phone/>} tone="blue"/></div>
    <div className="flex flex-col gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 md:flex-row md:items-center md:justify-between"><div className="flex flex-1 flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar contato, telefone ou e-mail" className="w-full rounded-xl border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-sm text-slate-100 outline-none focus:border-cyan-500"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200"><option value="TODOS">Todos os contatos</option><option value="VINCULADOS">Vinculados a clientes</option><option value="SEM_VINCULO">Sem vínculo</option></select></div><button onClick={()=>setOpen(!open)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-cyan-500"><Plus className="h-4 w-4"/>Novo Contato</button></div>
    {open&&<form onSubmit={add} className="grid gap-3 rounded-2xl border border-cyan-500/30 bg-slate-900 p-5 md:grid-cols-3"><h2 className="md:col-span-3 text-sm font-black text-slate-100">Cadastrar contato</h2><input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Nome da pessoa ou empresa" className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><input value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="Telefone / WhatsApp" className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><input type="email" value={form.email} onChange={e=>set('email',e.target.value)} placeholder="E-mail" className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Cargo / função" className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><select value={form.clientId} onChange={e=>set('clientId',e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"><option value="">Sem cliente vinculado</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="url" value={form.websiteUrl} onChange={e=>set('websiteUrl',e.target.value)} placeholder="Website (opcional)" className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><div className="md:col-span-3 flex gap-2"><button className="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-bold">Salvar contato</button><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold text-slate-300">Cancelar</button></div></form>}
    {message&&<p className="rounded-xl border border-emerald-500/30 bg-emerald-950/30 px-4 py-3 text-sm text-emerald-300">{message}</p>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item=><article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 transition hover:-translate-y-0.5 hover:border-cyan-500/40"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3">{item.photoUrl?<img src={item.photoUrl} alt="" className="h-11 w-11 rounded-full object-cover"/>:<div className="flex h-11 w-11 items-center justify-center rounded-full bg-cyan-500/15 text-lg font-black text-cyan-300">{item.name.slice(0,1).toUpperCase()}</div>}<div><h3 className="font-bold text-slate-100">{item.name}</h3><p className="text-xs text-slate-500">{item.title||'Contato operacional'}</p></div></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.clientId?'bg-emerald-500/10 text-emerald-300':'bg-amber-500/10 text-amber-300'}`}>{item.clientId?'Cliente':'Contato'}</span></div><div className="mt-5 space-y-2 text-xs text-slate-400">{item.phone&&<p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5 text-cyan-400"/>{item.phone}</p>}{item.email&&<p className="flex items-center gap-2 truncate"><Mail className="h-3.5 w-3.5 text-cyan-400"/>{item.email}</p>}{item.clientId&&<p className="flex items-center gap-2"><Building2 className="h-3.5 w-3.5 text-emerald-400"/>Cliente vinculado</p>}</div></article>)}</div>
    {!filtered.length&&<div className="rounded-2xl border border-dashed border-slate-700 p-10 text-center text-sm text-slate-500">Nenhum contato encontrado.</div>}
  </div>
}
function Metric({label,value,icon,tone}:{label:string,value:number,icon:React.ReactNode,tone:string}){const tones:Record<string,string>={cyan:'bg-cyan-500/10 text-cyan-400',emerald:'bg-emerald-500/10 text-emerald-400',amber:'bg-amber-500/10 text-amber-400',blue:'bg-blue-500/10 text-blue-400'};return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-xl ${tones[tone]||tones.cyan}`}>{icon}</div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-100">{value}</p></div>}
