import Link from 'next/link'
import { and, desc, eq } from 'drizzle-orm'
import { BadgeCheck, FileText, Plus, Send, TrendingUp, XCircle } from 'lucide-react'
import { clients, db, officialDocuments, serviceRequests } from '@/db'

export const dynamic='force-dynamic'
export const metadata={title:'Propostas · Hub RR'}

export default async function PropostasPage(){
  const rows=db?await db.select({id:officialDocuments.id,number:officialDocuments.docNumber,type:officialDocuments.docType,value:officialDocuments.totalValue,status:officialDocuments.status,issuedAt:officialDocuments.issuedAt,clientName:clients.name,service:serviceRequests.serviceType}).from(officialDocuments).innerJoin(clients,eq(officialDocuments.clientId,clients.id)).innerJoin(serviceRequests,eq(officialDocuments.serviceRequestId,serviceRequests.id)).where(and(eq(officialDocuments.docType,'ORCAMENTO'),eq(officialDocuments.status,'EMITIDO'))).orderBy(desc(officialDocuments.createdAt)).limit(100):[]
  const technical=db?await db.select({id:officialDocuments.id,number:officialDocuments.docNumber,type:officialDocuments.docType,value:officialDocuments.totalValue,status:officialDocuments.status,issuedAt:officialDocuments.issuedAt,clientName:clients.name,service:serviceRequests.serviceType}).from(officialDocuments).innerJoin(clients,eq(officialDocuments.clientId,clients.id)).innerJoin(serviceRequests,eq(officialDocuments.serviceRequestId,serviceRequests.id)).where(and(eq(officialDocuments.docType,'ORCAMENTO_TECNICO'),eq(officialDocuments.status,'EMITIDO'))).orderBy(desc(officialDocuments.createdAt)).limit(100):[]
  const proposals=[...rows,...technical];const total=proposals.reduce((a,p)=>a+Number(p.value||0),0)
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-400">Gestão comercial</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-black text-slate-100">Propostas <FileText className="h-5 w-5 text-cyan-400"/></h1><p className="mt-1 text-sm text-slate-400">Orçamentos emitidos, negociação e conversão em serviços da RR.</p></div><Link href="/portal/sofia-drafts" className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 py-3 text-sm font-bold text-white hover:bg-cyan-500"><Plus className="h-4 w-4"/>Nova proposta via Sofia</Link></header>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Total" value={proposals.length} icon={<FileText/>} tone="cyan"/><Metric label="Em negociação" value={proposals.length} icon={<Send/>} tone="amber"/><Metric label="Aprovadas" value={0} icon={<BadgeCheck/>} tone="emerald"/><Metric label="Recusadas" value={0} icon={<XCircle/>} tone="rose"/><Metric label="Valor proposto" value={new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(total)} icon={<TrendingUp/>} tone="blue"/></div>
  <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-amber-500/10 px-3 py-1.5 text-xs font-bold text-amber-300">Em negociação · {proposals.length}</span><span className="rounded-full bg-emerald-500/10 px-3 py-1.5 text-xs font-bold text-emerald-300">Aprovadas · 0</span><span className="rounded-full bg-slate-800 px-3 py-1.5 text-xs font-bold text-slate-400">Não contabilizar · 0</span></div></div>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{proposals.map(p=><article key={p.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 hover:border-cyan-500/40"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-bold text-cyan-400">{p.number}</p><h2 className="mt-2 font-bold text-slate-100">{p.clientName}</h2></div><span className="rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-bold uppercase text-amber-300">Em negociação</span></div><p className="mt-4 text-sm text-slate-400">{p.service||'Serviço RR'}</p><div className="mt-4 flex items-end justify-between border-t border-slate-800 pt-4"><div><p className="text-xs text-slate-500">Valor</p><p className="mt-1 text-lg font-black text-emerald-300">{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(p.value||0))}</p></div><Link href={`/portal/documentos/preview/${p.id}`} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-cyan-300 hover:bg-slate-800">Abrir PDF</Link></div></article>)}</div>{!proposals.length&&<div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center"><FileText className="mx-auto h-10 w-10 text-slate-600"/><p className="mt-3 font-bold text-slate-300">Nenhuma proposta emitida</p><p className="mt-1 text-sm text-slate-500">Os orçamentos criados pela Sofia aparecerão aqui.</p></div>}</div>
}
function Metric({label,value,icon,tone}:{label:string,value:string|number,icon:React.ReactNode,tone:'cyan'|'amber'|'emerald'|'rose'|'blue'}){const colors={cyan:'text-cyan-400 bg-cyan-500/10',amber:'text-amber-400 bg-amber-500/10',emerald:'text-emerald-400 bg-emerald-500/10',rose:'text-rose-400 bg-rose-500/10',blue:'text-blue-400 bg-blue-500/10'};return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-xl ${colors[tone]}`}>{icon}</div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-slate-100">{value}</p></div>}
