'use client'
import { useState } from 'react'
import { BadgeCheck, FileText, Send, XCircle } from 'lucide-react'
import { PROPOSAL_STATUSES } from '@/lib/proposals'

type Proposal={id:string,title:string,totalValue:string, status:string, clientName:string, service:string|null, officialDocumentId:string|null}
export default function PropostasClient({initial}:{initial:Proposal[]}){const [items,setItems]=useState(initial);const [message,setMessage]=useState('');const fmt=(v:string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));async function change(id:string,status:string){const res=await fetch('/api/proposals',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});const data=await res.json();if(!res.ok){setMessage(data.error||'Não foi possível atualizar.');return}setItems(xs=>xs.map(x=>x.id===id?{...x,status}:x));setMessage('Status atualizado com auditoria.')}const count=(s:string)=>items.filter(x=>x.status===s).length;const total=items.reduce((a,x)=>a+Number(x.totalValue),0);return <div className="space-y-6"><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric l="Total" v={items.length}/><Metric l="Em negociação" v={count(PROPOSAL_STATUSES.NEGOTIATION)}/><Metric l="Aprovadas" v={count(PROPOSAL_STATUSES.APPROVED)}/><Metric l="Recusadas" v={count(PROPOSAL_STATUSES.REJECTED)}/><Metric l="Valor total" v={fmt(String(total))}/></div>{message&&<p className="rounded-xl border border-cyan-500/30 bg-cyan-950/30 px-4 py-3 text-sm text-cyan-200">{message}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(p=><article key={p.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-slate-100">{p.title}</h2><p className="mt-1 text-xs text-slate-400">{p.clientName} · {p.service||'Serviço RR'}</p></div><Status status={p.status}/></div><p className="mt-5 text-xl font-black text-emerald-300">{fmt(p.totalValue)}</p><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-800 pt-4">{p.status===PROPOSAL_STATUSES.DRAFT&&<button onClick={()=>change(p.id,PROPOSAL_STATUSES.SENT)} className="rounded-lg bg-cyan-600 px-3 py-2 text-xs font-bold">Marcar enviada</button>}{[PROPOSAL_STATUSES.SENT,PROPOSAL_STATUSES.NEGOTIATION].includes(p.status as typeof PROPOSAL_STATUSES.SENT|typeof PROPOSAL_STATUSES.NEGOTIATION)&&<><button onClick={()=>change(p.id,PROPOSAL_STATUSES.APPROVED)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold">Aprovar</button><button onClick={()=>change(p.id,PROPOSAL_STATUSES.REJECTED)} className="rounded-lg border border-rose-700 px-3 py-2 text-xs font-bold text-rose-300">Recusar</button></>}{p.officialDocumentId&&<a href={`/portal/documentos/preview/${p.officialDocumentId}`} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold text-cyan-300">Abrir PDF</a>}</div></article>)}</div>{!items.length&&<div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center text-sm text-slate-500">Nenhuma proposta cadastrada. As propostas criadas pela Sofia ou pelo Hub aparecerão aqui.</div>}</div>}
function Metric({l,v}:{l:string,v:string|number}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-xl font-black text-slate-100">{v}</p></div>}
function Status({status}:{status:string}){const labels:Record<string,string>={DRAFT:'Rascunho',SENT:'Enviada',NEGOTIATION:'Em negociação',APPROVED:'Aprovada',REJECTED:'Recusada',EXPIRED:'Expirada',CANCELLED:'Cancelada',NOT_COUNTED:'Não contabilizar'};return <span className="h-fit rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-bold uppercase text-amber-300">{labels[status]||status}</span>}
