'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Save, Loader2 } from 'lucide-react';
export default function EditChamadoForm({ initial }: { initial: any }) {
 const router=useRouter(); const [form,setForm]=useState(initial); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
 const ch=(e:any)=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async(e:any)=>{e.preventDefault(); setLoading(true); const res=await fetch(`/api/chamados/${initial.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const data=await res.json().catch(()=>({})); if(!res.ok){setError(data.error||'Erro ao salvar'); setLoading(false); return;} router.push('/portal/chamados'); router.refresh();};
 return <form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900/60 p-6">{error&&<div className="rounded-xl border border-red-800 bg-red-950/50 p-3 text-xs text-red-200">{error}</div>}<div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Select name="serviceType" label="Serviço" value={form.serviceType} onChange={ch} options={['DESENTUPIMENTO','HIDROJATEAMENTO','CAIXA_GORDURA','LIMPA_FOSSA','DEDETIZACAO']} /><Select name="priority" label="Prioridade" value={form.priority} onChange={ch} options={['NORMAL','URGENTE_24H']} /><Select name="status" label="Status" value={form.status} onChange={ch} options={['PENDING_REVIEW','AGENDADO','EM_EXECUCAO','CONCLUIDO','CANCELADO']} /><Field name="totalAmount" label="Valor" value={form.totalAmount||'0.00'} onChange={ch}/><Field name="paymentMethod" label="Pagamento" value={form.paymentMethod||'Pix'} onChange={ch}/><Field name="warrantyDays" label="Garantia (dias)" value={form.warrantyDays||30} onChange={ch}/></div><Area name="problemReported" label="Problema relatado" value={form.problemReported||''} onChange={ch} required/><Area name="problemFound" label="Problema encontrado" value={form.problemFound||''} onChange={ch}/><Area name="internalNotes" label="Notas internas" value={form.internalNotes||''} onChange={ch}/><Area name="customerNotes" label="Observações ao cliente" value={form.customerNotes||''} onChange={ch}/><button disabled={loading} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 py-3 text-sm font-bold text-white hover:bg-cyan-500 disabled:opacity-50">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<Save className="w-4 h-4"/>} Salvar chamado</button></form>
}
function Field(p:any){return <label className="block"><span className="text-xs font-bold uppercase text-slate-300">{p.label}</span><input {...p} label={undefined} className="mt-1 w-full rounded-xl border border-slate-800 bg-slate-950 p-3 text-sm text-slate-100"/></label>}
function Area(p:any){return <label className="block"><span className="text-xs font-bold uppercase text-slate-300">{p.label}</span><textarea {...p} label={undefined} rows={3} className="mt-1 w-full rounded-xl border border-slate-800 bg-slate-950 p-3 text-sm text-slate-100"/></label>}
function Select({name,label,value,onChange,options}:any){return <label className="block"><span className="text-xs font-bold uppercase text-slate-300">{label}</span><select name={name} value={value} onChange={onChange} className="mt-1 w-full rounded-xl border border-slate-800 bg-slate-950 p-3 text-sm text-slate-100">{options.map((o:string)=><option key={o} value={o}>{o}</option>)}</select></label>}
