import { NextResponse } from 'next/server'
import { and, asc, eq } from 'drizzle-orm'
import { db, vehicles } from '@/db'
import { requireLocalPermission } from '@/lib/require-local-permission'
const text = (value: unknown) => typeof value === 'string' ? value.trim() || null : null
export async function GET() { if (!await requireLocalPermission('operations.read') || !db) return NextResponse.json({error:'Não autorizado'},{status:db?403:503}); return NextResponse.json({ vehicles: await db.select().from(vehicles).orderBy(asc(vehicles.name)) }) }
export async function POST(request: Request) { if (!await requireLocalPermission('operations.write') || !db) return NextResponse.json({error:'Não autorizado'},{status:db?403:503}); const body=await request.json(); const name=text(body.name); if(!name)return NextResponse.json({error:'O nome do veículo é obrigatório.'},{status:400}); const [vehicle]=await db.insert(vehicles).values({name,plate:text(body.plate),type:text(body.type),description:text(body.description),notes:text(body.notes),teamId:text(body.teamId),isActive:body.isActive!==false}).returning(); return NextResponse.json({vehicle},{status:201}) }
export async function PATCH(request: Request) { if (!await requireLocalPermission('operations.write') || !db) return NextResponse.json({error:'Não autorizado'},{status:db?403:503}); const body=await request.json(); const id=text(body.id); if(!id)return NextResponse.json({error:'Veículo inválido.'},{status:400}); const values:Record<string,unknown>={updatedAt:new Date()}; for(const key of ['name','plate','type','description','notes','teamId'] as const)if(body[key]!==undefined)values[key]=text(body[key]); if(typeof body.isActive==='boolean')values.isActive=body.isActive; if(values.name===null)return NextResponse.json({error:'O nome do veículo é obrigatório.'},{status:400}); const [vehicle]=await db.update(vehicles).set(values as any).where(eq(vehicles.id,id)).returning(); return vehicle?NextResponse.json({vehicle}):NextResponse.json({error:'Veículo não encontrado.'},{status:404}) }
export async function DELETE(request: Request) { if (!await requireLocalPermission('operations.write') || !db) return NextResponse.json({error:'Não autorizado'},{status:db?403:503}); const id=new URL(request.url).searchParams.get('id'); if(!id)return NextResponse.json({error:'Veículo inválido.'},{status:400}); const [vehicle]=await db.update(vehicles).set({isActive:false,updatedAt:new Date()}).where(and(eq(vehicles.id,id),eq(vehicles.isActive,true))).returning(); return vehicle?NextResponse.json({success:true,vehicle}):NextResponse.json({error:'Veículo não encontrado ou já arquivado.'},{status:404}) }
