import Link from 'next/link'
import { desc } from 'drizzle-orm'
import { PlusCircle, UserRoundPlus } from 'lucide-react'
import { db, leads } from '@/db'
import { requireLocalPermission } from '@/lib/require-local-permission'
import { redirect } from 'next/navigation'
export const dynamic = 'force-dynamic'
export const metadata = { title: 'Leads · Hub RR' }
const labels: Record<string, string> = { NEW: 'Novo', QUOTING: 'Em orçamento', APPROVED: 'Aprovado', LOST: 'Perdido', CONVERTED: 'Convertido' }
export default async function LeadsPage() { if (!await requireLocalPermission('crm.read')) redirect('/portal'); const rows = db ? await db.select().from(leads).orderBy(desc(leads.updatedAt)).limit(200) : []; return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-400">Pré-atendimento comercial</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-black text-slate-100">Leads <UserRoundPlus className="h-5 w-5 text-cyan-400" /></h1><p className="mt-1 text-sm text-slate-400">Contatos em avaliação antes de se tornarem clientes. A carteira CRM atual permanece separada.</p></div><Link href="/portal/leads/novo" className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 py-3 text-sm font-bold text-white hover:bg-cyan-500"><PlusCircle className="h-4 w-4" />Novo lead</Link></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(lead => <Link key={lead.id} href={`/portal/leads/${lead.id}`} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 transition hover:border-cyan-500/50"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-slate-100">{lead.name}</h2><p className="mt-1 text-sm text-slate-400">{lead.phone}</p></div><span className="rounded-full bg-cyan-500/10 px-2 py-1 text-[10px] font-bold uppercase text-cyan-300">{labels[lead.status] || lead.status}</span></div><p className="mt-5 text-xs text-slate-500">{lead.serviceType || 'Serviço a confirmar'} · atualizado {lead.updatedAt.toLocaleDateString('pt-BR')}</p></Link>)}</div>{!rows.length && <div className="rounded-2xl border border-dashed border-slate-700 p-12 text-center text-sm text-slate-500">Nenhum Lead cadastrado. Crie o primeiro contato comercial sem alterar o CRM de Clientes.</div>}</div> }
